### ISSUE TITLE
Poi geometry of type MultiPoint breaks ogr2osm

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-backend#207]
`ogr2osm.py` is not able to handle geometries of type MultiPoint, crashing with an error.

```
[11:55:53.660 +0.983] [p5 s6 proj-setup] error Error: Traceback (most recent call last):
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 750, in <module>
    parseData(data)
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 346, in parseData
    parseLayer(translations.filterLayer(layer))
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 410, in parseLayer
    parseFeature(translations.filterFeature(ogrfeature, fieldNames, reproject), fieldNames, reproject)
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 420, in parseFeature
    geometries = parseGeometry([ogrgeometry])
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 458, in parseGeometry
    returngeometries.extend(parseCollection(ogrgeometry))
  File "/guts/projects/rra/app/lib/ogr2osm/ogr2osm.py", line 545, in parseCollection
    member.addparent(geometry)
AttributeError: 'list' object has no attribute 'addparent'

    at ChildProcess.<anonymous> (/guts/projects/rra/app/services/rra-osm-p2p.js:156:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

This should be validated when the file us uploaded throwing an error, or doing an automatic conversion.

**Comment by olafveerman** [comment]
In the short term, I think we can go with validation on file upload and reject the file, or ignore the Multipoints.

Longer run we can make it more elegant. In some of the test data, the Multipoints have a single set of coordinates. These can easily be turned into regular Point features.
As for dealing with real Multipoints, we should figure out what the best way to handle those are. Split them into single features? Take the center point?

**Comment by danielfdsilva** [comment]
This came up again and the solution was to get the center of the Multipoints. This is being done for pois.
