### ISSUE TITLE
RN upload - Request Time-out

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-backend#247]
Uploading a 170mb OSM XML file with road network data, I get the following error on the frontend:

`An error occurred while uploading the road network file: Request Time-out`

No file is in the S3 bucket.

CloudWatch logs

```
15:19:02 RangeError: Array buffer allocation failed
15:19:02 at new ArrayBuffer (<anonymous>)
15:19:02 at createUnsafeArrayBuffer (buffer.js:93:12)
15:19:02 at createUnsafeBuffer (buffer.js:87:25)
15:19:02 at allocate (buffer.js:293:12)
15:19:02 at Function.Buffer.allocUnsafe (buffer.js:254:10)
15:19:02 at Function.Buffer.concat (buffer.js:441:23)
15:19:02 at Block._transform (/dist/node_modules/block-stream2/index.js:30:24)
15:19:02 at Block.Transform._read (/dist/node_modules/readable-stream/lib/_stream_transform.js:184:10)
15:19:02 at Block.Transform._write (/dist/node_modules/readable-stream/lib/_stream_transform.js:172:83)
15:19:02 at doWrite (/dist/node_modules/readable-stream/lib/_stream_writable.js:428:64)
15:19:02 at writeOrBuffer (/dist/node_modules/readable-stream/lib/_stream_writable.js:417:5)
15:19:02 at Block.Writable.write (/dist/node_modules/readable-stream/lib/_stream_writable.js:334:11)
15:19:02 at Readable.ondata (_stream_readable.js:639:20)
15:19:02 at emitOne (events.js:116:13)
15:19:02 at Readable.emit (events.js:211:7)
15:19:02 at Readable.read (_stream_readable.js:475:10)
15:19:02 at flow (_stream_readable.js:846:34)
15:19:02 at emitReadable_ (_stream_readable.js:514:3)
15:19:02 at _combinedTickCallback (internal/process/next_tick.js:136:11)
15:19:02 at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

cc @danielfdsilva

**Comment by olafveerman** [comment]
Some more notes:

* this seems to be a bug introduced in https://github.com/WorldBank-Transport/ram-backend/releases/tag/v0.8.1. Reverting back to `0.8.0`, doesn't show the same behavior.
* a small file (5MB) uploaded without any issues.
